[package]
org = "masterbank"
name = "bian_services"
version = "0.1.0"
distribution = "2201.8.4"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.10.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.9.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.4.0"
