[container.image]
repository="masterbank"
name="bian-services"
tag="0.1.0"

[cloud.deployment]
min_memory="256Mi"
max_memory="512Mi"
min_cpu="200m"
max_cpu="1000m"

[cloud.deployment.autoscaling]
min_replicas=1
max_replicas=3
cpu_percentage=80
memory_percentage=80

[cloud.deployment.probes]
liveness_probe.port=8080
readiness_probe.port=8080

[cloud.config]
config_maps=[
    {
        name="api-config",
        mount_path="/config",
        data=[
            {
                key="config.json",
                value="""
                {
                    "api_version": "v1",
                    "environment": "production"
                }
                """
            }
        ]
    }
]
