[container.image]
repository="choreocontrolplane.azurecr.io"
name="masterbank-bian-services"
tag="0.1.0"

[cloud.deployment]
min_memory="256Mi"
max_memory="512Mi"
min_cpu="200m"
max_cpu="1000m"

[cloud.deployment.autoscaling]
min_replicas=1
max_replicas=3
cpu_percentage=80
memory_percentage=80

[cloud.config]
region="us-east-1"
organization="masterbank"

[build.ballerina]
repository="central.ballerina.io"
use_project_repository=true
